---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: aws-package
spec:
  interval: 1h0m0s
  url: oci://ghcr.io/flux-iac/aws-primitive-modules
  ref:
    tag: v4.38.0-v1alpha11
