apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- cluster_role_binding.yaml
- service_account.yaml
- runner_role.yaml
- runner_role_binding.yaml
namePrefix: tf-
