apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - planner.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: flux-iac/branch-planner
    newName: ghcr.io/flux-iac/branch-planner
    newTag: v0.16.0-rc.4
