name: helm-test
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'charts/tofu-controller/**'
      - '.github/workflows/helm-test.yaml'

permissions: read-all

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b80ff79f1755d06ba70441c368a6fe801f5f3a62 # v4.0.0
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v3.5.0
        with:
          version: latest

      - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: "3.10"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run docs-testing (helm-docs)
        id: helm-docs
        run: |
          make helm-docs
          if [[ $(git diff --stat) != '' ]]; then
            echo -e '\033[0;31mDocumentation outdated! (Run make helm-docs locally and commit)\033[0m ❌'
            git diff --color
            exit 1
          else
            echo -e '\033[0;32mDocumentation up to date\033[0m ✔'
          fi
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (lint)
        run: ct lint --check-version-increment=false --config ct.yaml
        if: steps.list-changed.outputs.changed == 'true'

      - name: Build the tofu-controller container image
        run: |
          make docker-buildx MANAGER_IMG=test/tofu-controller RUNNER_IMG=test/tf-runner TAG=ct \
            BUILD_ARGS="--load"
        if: steps.list-changed.outputs.changed == 'true'

      - name: Create kind cluster
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Load test images into KIND
        run: |
          kind load docker-image --name=chart-testing test/tofu-controller:ct
          kind load docker-image --name=chart-testing test/tf-runner:ct
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install Flux CLI
        uses: fluxcd/flux2/action@896e0fa46d5107a05e953dd0a5261d78a145ec8c # main
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install Source controller
        run: flux install --components=source-controller
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml
        if: steps.list-changed.outputs.changed == 'true'
