name: helm-test
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'charts/tofu-controller/**'
      - '.github/workflows/helm-test.yaml'

permissions: read-all

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.0.0
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v3.5.0
        with:
          version: latest

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.10"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run docs-testing (helm-docs)
        id: helm-docs
        run: |
          make helm-docs
          if [[ $(git diff --stat) != '' ]]; then
            echo -e '\033[0;31mDocumentation outdated! (Run make helm-docs locally and commit)\033[0m ❌'
            git diff --color
            exit 1
          else
            echo -e '\033[0;32mDocumentation up to date\033[0m ✔'
          fi
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (lint)
        run: ct lint --check-version-increment=false --config ct.yaml
        if: steps.list-changed.outputs.changed == 'true'

      - name: Build the tofu-controller container image
        run: |
          make docker-buildx MANAGER_IMG=test/tofu-controller RUNNER_IMG=test/tf-runner TAG=ct \
            BUILD_ARGS="--load"
        if: steps.list-changed.outputs.changed == 'true'

      - name: Create kind cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Load test images into KIND
        run: |
          kind load docker-image --name=chart-testing test/tofu-controller:ct
          kind load docker-image --name=chart-testing test/tf-runner:ct
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install Flux CLI
        uses: fluxcd/flux2/action@8454b02a32e48d775b9f563cb51fdcb1787b5b93 # main
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install Source controller
        run: flux install --components=source-controller
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml
        if: steps.list-changed.outputs.changed == 'true'
